name: TD_M2
channels:
  - conda-forge
  - fredboudon
  - defaults
dependencies:
  #- python #=3.8
  #- alinea.caribu
  - openalea.lpy
  #- openalea.mtg
  #- openalea.plantgl
  #- pyopengl=3.1.5
