name: TD_M2
channels:
  - conda-forge
  - fredboudon
  - defaults
dependencies:
  - python #=3.8
  - pip:
    - pyrender
  #- alinea.caribu
  #- openalea.lpy
  #- openalea.mtg
  #- openalea.plantgl
  - pyopengl
